App init
Insei/make-gray-image pull request #1
Opened 2022-09-20 09:57 UTC by BadikVV

2022-09-20 11:18 UTC, lordspinach requested changes
Нужно исправить все замечания. На созвоне включим чтобы все варнинги были ошибками и все вытекающее надо будет поправить

2022-09-20 11:18 UTC, lordspinach commented on MakeGreyImageAPI/Interfaces/IImageService.cs
> +public interface IImageService
Нужно добавить описание, для чего этот интерфейс, чем он будет заниматься

2022-09-20 11:18 UTC, lordspinach commented on MakeGreyImageAPI/Interfaces/IImageService.cs
> +    public Image ConvertToGrey (Image image);
Так же для каждого метода внутри интерфейса нужно свое описание. Они добавляются через ///, там описываются то что делает метод, что принимает и что отдает

2022-09-20 11:18 UTC, lordspinach commented on MakeGreyImageAPI/Program.cs
> +// builder.Services.AddControllers();
Нужно убрать неиспользуемый код

2022-09-20 11:18 UTC, lordspinach commented on MakeGreyImageAPI/Program.cs
> +// #pragma warning restore CA1416
Нужно убрать неиспользуемый код

2022-09-20 11:18 UTC, lordspinach commented on MakeGreyImageAPI/Program.cs
> +builder.Services.AddCors(options =>
Нужно добавить комментарий, для чего этот блок кода. У нас это нужно для запросов с локал хоста, для работы без подписанного сертификата и тут же мы разрешаем использование любых HTTP методов и хидеров

2022-09-20 11:18 UTC, lordspinach commented on MakeGreyImageAPI/Controllers/ImageController.cs
> +      public IFormFile files { get; set; }
Почему переменная называется files? (во множественном числе) Я не вижу там нескольких файлов

2022-09-20 11:18 UTC, lordspinach commented on MakeGreyImageAPI/Controllers/ImageController.cs
> +         await using (var memoryStream = new MemoryStream())
Нужно перенести весь код начиная с 43 строки в сервис, тк тут логика обработки изображения и с контроллером она не связана

2022-09-20 11:18 UTC, lordspinach commented on MakeGreyImageAPI/Controllers/ImageController.cs
> +               greyImg.Save(_environment.WebRootPath + "\\Upload\\" + objFile.files.FileName);
Необходимо убрать сохранение картинки на диск

2022-09-20 12:26 UTC, BadikVV commented on MakeGreyImageAPI/Controllers/ImageController.cs
> +      public IFormFile files { get; set; }
первоначально объект files использовался для дальнейшего приема множества картинок и обхода каждой из них для конвертации

2022-09-20 14:14 UTC, lordspinach commented on MakeGreyImageAPI/Controllers/ImageController.cs
> +      public IFormFile files { get; set; }
Если сейчас он использует одну картинку - надо назвать соответственно. Позже переименуешь при необходимости

2022-09-21 09:01 UTC, lordspinach approved these changes

2022-09-21 09:02 UTC, merged