Image entity
Insei/make-gray-image pull request #3
Opened 2022-10-07 14:33 UTC by BadikVV

2022-10-10 09:28 UTC, lordspinach requested changes

2022-10-10 09:28 UTC, lordspinach commented on MakeGreyImageAPI.DTOs/LocalImageConvertTaskCreateDTO.cs
> +    // public ConvertParameters Parameters { get; set; }
Почему строка закомментирована?

2022-10-10 09:28 UTC, lordspinach commented on MakeGreyImageAPI.DTOs/LocalImageDTO.cs
> +    /// </summary>
Не понял. Здесь есть описание поля класса а в других местах нет.  Надо добавить

2022-10-10 09:28 UTC, lordspinach commented on MakeGreyImageAPI.DTOs/PaginationListResponse.cs
> +    /// </summary>
Без комментариев. По комментам тебе везде надо пройтись, ты их не сделал. Дальше на них не обращаю внимания

2022-10-10 09:28 UTC, lordspinach commented on MakeGreyImageAPI/Controllers/LocalImageController.cs
> +            Data = image
Не вижу смысла тут создавать переменную. Ты выше, на 46 строке записал сразу результат в респонс. Сделай так же

2022-10-10 09:28 UTC, lordspinach commented on MakeGreyImageAPI/Controllers/LocalImageConvertTaskController.cs
> +            Data = localImageConvert
await _imageConvertService.GetById(id); нужно вызвать прямо тут

2022-10-10 09:28 UTC, lordspinach commented on MakeGreyImageAPI/Controllers/LocalImageConvertTaskController.cs
> +    public async Task<IActionResult> Download(Guid id)
Что-то я не понял зачем тут этот метод, это же контроллер тасков, почему ты тут качаешь картинку?

2022-10-10 09:28 UTC, lordspinach commented on MakeGreyImageAPI/Managers/ImageManager.cs
> +                // var bmpImg = (Bitmap)img;
Надо удалить неиспользуемый код. Это строчка и чуть выше

2022-10-10 09:28 UTC, lordspinach commented on MakeGreyImageAPI/Program.cs
> +builder.Services.AddDbContext<DataDbContext>(options =>
Стоит добавить комментарий почему наше приложение работает в Singleton режиме

2022-10-10 09:28 UTC, lordspinach commented on MakeGreyImageAPI/Services/ImageService.cs
> +        var image = _repository.GetById<LocalImage>(id);
Здесь нужен await вместо ожидания у маппера и вызова .Result в методе Update()

2022-10-10 09:28 UTC, lordspinach commented on MakeGreyImageAPI/Services/LocalImageConvertTaskService.cs
> +        await Task.Delay(5000);
Задержка была для тестов, ее надо убрать

2022-10-10 09:28 UTC, lordspinach commented on MakeGreyImageAPI/Services/LocalImageConvertTaskService.cs
> +        // result.Parameters.Extension = localImage!.Extension;
Этот кусок надо вернуть

2022-10-10 09:28 UTC, lordspinach commented on MakeGreyImageAPI/Services/LocalImageConvertTaskService.cs
> +        var imageConvertTask = _repository.GetById<LocalImageConvertTask>(id);
Писал про аналогичную проблему выше. Await должен быть на этой строчке

2022-10-17 13:31 UTC, lordspinach requested changes

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI.DTOs/LocalImageConvertTaskCreateDTO.cs
> +    // public ConvertParameters? Parameters { get; set; }
Почему закомментировано?

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI.DTOs/LocalImageUpdateDTO.cs
> +public class LocalImageUpdateDTO : LocalImageBaseDTO
Мы же убрали обновление картинки. Соответственно ДТО тоже не должно быть

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI.DTOs/Results/PaginatedResult.cs
> +    public Pagination()
По сути тут дубликат. У тебя выше конструктор с принимаемыми параметрами, которым надо просто назначить дефолтное значение и избавиться от пустого конструктора

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI/Controllers/LocalImageController.cs
> +        Ok("Successfully");
Тут должен быть 204 HTTP код

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI/Controllers/LocalImageController.cs
> +        try
У нас обработка ошибок будет в middleware, а от try catch в контроллере я тебе говорил избавиться, почему тут он есть?

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI/Controllers/LocalImageConvertTaskController.cs
> +        try
Опять try catch, почему он тут?

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI/Controllers/LocalImageConvertTaskController.cs
> +        Ok("Successfully");
Должен быть 204 HTTP код

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI/Entities/EntityResult.cs
> +public class ResultStatus
Разве мы это используем где-то? Мы перешли на возврат ДТО и ActionResult, это надо убрать

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI/Infrastructure/Generics/GenericRepository.cs
> +    public async Task<TEntity> Insert<TEntity>(TEntity? entity) where TEntity : class
Почему здесь entity nullable объект?

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI/Program.cs
> +//and then each subsequent request will use the same instance
Ты тут написал что такое Singleton, а я говорил написать почему у наших сервисов такой жизненный цикл. Мы же это сделали, потому что у нас есть работа с репозиторием в асинхронном режиме, когда запрос уже завершен

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI/Services/ImageService.cs
> +        if(image == null) throw new BadHttpRequestException("Entity not found");
Здесь не BadRequest должен быть, а NotFound

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI/Services/ImageService.cs
> +    private static Task <Image> ConvertToSystemImageFormat(IFormFile image)
Что-то я не понимаю зачем тут Task нужен. Почему не вернуть просто Image?

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI/Services/LocalImageConvertTaskService.cs
> +        // result.Parameters.Extension = localImage!.Extension;
Не понял почему ты закрыл этот коммент, если ничего не исправлено

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI/Services/LocalImageConvertTaskService.cs
> +        if(imageConvertTask == null) throw new BadHttpRequestException("Entity not found");
Здесь не BadRequest должен быть, а NotFound

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI/Services/LocalImageConvertTaskService.cs
> +        if (imageConvertTask == null) throw new BadHttpRequestException("Entity not found");
И снова, здесь не BadRequest должен быть, а NotFound

2022-10-17 13:31 UTC, lordspinach commented on MakeGreyImageAPI/Validators/CreateImageConvertTaskValidator.cs
> +            .Must(IsImageExist).WithMessage("Image with this ID {PropertyName} does not exist");
ID {PropertyName}? Выглядит как ошибка, поправь меня если это не так

2022-10-17 13:37 UTC, Insei commented on MakeGreyImageAPI/Controllers/LocalImageController.cs
> +        if (result != null) return Ok(result);
@lordspinach Так здесь смысл в том, что тут идёт поиск в сервисе, если картинка найдена, то это одно, а если не найдена, то можно вернуть NotFound()

2022-10-17 13:40 UTC, Insei commented on MakeGreyImageAPI/Program.cs
> +//and then each subsequent request will use the same instance
Я думаю, этот момент надо вам повторить

2022-10-17 13:52 UTC, lordspinach commented on MakeGreyImageAPI/Program.cs
> +//and then each subsequent request will use the same instance
На созвоне еще раз объясню

2022-10-18 09:12 UTC, BadikVV commented on MakeGreyImageAPI/Services/LocalImageConvertTaskService.cs
> +        // result.Parameters.Extension = localImage!.Extension;
Вернул

2022-10-18 09:12 UTC, BadikVV commented on MakeGreyImageAPI/Program.cs
> +//and then each subsequent request will use the same instance
Переписал

2022-10-18 09:13 UTC, BadikVV commented on MakeGreyImageAPI/Services/ImageService.cs
> +        if(image == null) throw new BadHttpRequestException("Entity not found");
Поправил!

2022-10-18 09:14 UTC, BadikVV commented on MakeGreyImageAPI/Services/LocalImageConvertTaskService.cs
> +        if(imageConvertTask == null) throw new BadHttpRequestException("Entity not found");
Исправил

2022-10-18 09:14 UTC, BadikVV commented on MakeGreyImageAPI/Services/LocalImageConvertTaskService.cs
> +        if (imageConvertTask == null) throw new BadHttpRequestException("Entity not found");
Исправил

2022-10-18 09:14 UTC, BadikVV commented on MakeGreyImageAPI/Validators/CreateImageConvertTaskValidator.cs
> +            .Must(IsImageExist).WithMessage("Image with this ID {PropertyName} does not exist");
Добавил PropertyValue

2022-10-18 09:17 UTC, lordspinach approved these changes
Ок

2022-10-18 09:18 UTC, merged