added error logging to ErrorHandlerMiddleware
Insei/make-gray-image pull request #7
Opened 2022-10-20 12:31 UTC by BadikVV

created logging for ErrorHandlerMiddleware

2022-10-20 14:38 UTC, lordspinach requested changes

2022-10-20 14:38 UTC, lordspinach commented on MakeGreyImageAPI/Middlewares/ErrorHandlerMiddleware.cs
> +            // // TODO: add logging
Забыл убрать TODO

2022-10-20 14:38 UTC, lordspinach commented on MakeGreyImageAPI/Middlewares/ErrorHandlerMiddleware.cs
> +        if (context.Request.HasFormContentType && context.Request.Form.Any())
У нас Form только для передачи файла используется и передавать value файла в лог не вижу смысла, там будет нечитаемое месиво. Остальные параметры у нас идут как Query и они у тебя не залогируются, надо добавить

2022-10-21 07:42 UTC, BadikVV commented on MakeGreyImageAPI/Middlewares/ErrorHandlerMiddleware.cs
> +            // // TODO: add logging
Убрал

2022-10-21 07:43 UTC, BadikVV commented on MakeGreyImageAPI/Middlewares/ErrorHandlerMiddleware.cs
> +        if (context.Request.HasFormContentType && context.Request.Form.Any())
Поправил

2022-10-21 08:04 UTC, lordspinach approved these changes, later dismissed

2022-10-21 08:56 UTC, lordspinach approved these changes

2022-10-21 08:56 UTC, merged